eventdetail/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('',views.eventdetail,name='index'),
    path('details/<int:event_id>', views.details, name ='details'),
]

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('',views.home,name='index'),

]

post/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('createpost/',views.post,name='postevent'),
    path('',views.home,name='index'),
]

sign/urls.py
from django.urls import path
from sign import views

urlpatterns = [
    path('',views.login,name='login'),
    path('register/',views.register,name='register'),
]

t_k/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from sign import views

urlpatterns = [
	path('',include('home.urls'), name= 'home'),
    path('admin/', admin.site.urls),
    path('login/',include('sign.urls'), name= 'sign'),
    path('',include('home.urls')),
    path('post/',include('post.urls')),
    path('event/',include('eventdetail.urls', namespace='event'))
]

eventdetail/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

from django.db import models

# Create your models here.

post/models.py
from django.db import models
# Create your models here.


class Post(models.Model):
    nama_Kegiatan = models.CharField(max_length = 20)
    Lomba = models.BooleanField()
    Organisasi = models.BooleanField()
    Seminar = models.BooleanField()
    tanggal = models.DateField()
    lokasi = models.CharField(max_length = 20)
    contact = models.TextField()
    deskripsi = models.TextField()
    syarat_dan_ketentuan = models.TextField()

sign/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.user.username

home/forms.py
from django import forms

post/forms.py
from django import forms
from .models import Post
##Create your forms here
class PostForm(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = Post
        fields = '__all__'
        widgets = {
          'contact': forms.Textarea(attrs={'rows':4, 'cols':25}),
          'deskripsi': forms.Textarea(attrs={'rows':4, 'cols':25}),
          'syarat_dan_ketentuan': forms.Textarea(attrs={'rows':4, 'cols':25}),
        }

sign/forms.py
from django import forms
from sign.models import UserInfo
from django.contrib.auth.models import User

class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control login-input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control login-input'}))

class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta():
        model = User
        fields = ('username', 'password','password_repeat')	

eventdetail/views.py
from django.shortcuts import render
from post.models import Post

# Create your views here.
def eventdetail(request):
    return render(request,'pages/event.html',{})

def details(request, event_id):
	# context = {}
	catch = Post.objects.filter(id=event_id)[0]
	context = {
		'catch' : catch
	}
	html = 'pages/event.html'
	return render(request, html, context)

home/views.py
from django.shortcuts import render,redirect

from django.db.models import Q
from post.models import Post

def home(request):
    object_list = Post.objects.all()
    context = {'table_list' : object_list}
    query = request.GET.get('q')
    if(query):
        object_list = Post.objects.filter(
            Q(nama_Kegiatan__icontains=query) | Q(deskripsi__icontains=query)
        )
        context['table_list'] = object_list
    filterkategori = request.GET.get('filter')
    if(filterkategori):
        if(filterkategori=='organisasi'):
           context['table_list'] = Post.objects.filter(Organisasi=True)
        elif(filterkategori=='seminar'):
            context['table_list'] = Post.objects.filter(Seminar = True)
        elif(filterkategori=='lomba'):
            context['table_list']  = Post.objects.filter(Lomba = True)
    return render(request,'pages/index.html', context)

post/views.py
from django.shortcuts import render,redirect,reverse
from .models import Post
from .forms import PostForm
from django.db.models import Q

# Create your views here.
def home(request):
    object_list = Post.objects.all()
    context = {'table_list' : object_list}
    query = request.GET.get('q')
    if(query):
        object_list = Post.objects.filter(
            Q(nama_Kegiatan__icontains=query) | Q(deskripsi__icontains=query)
        )
        context['table_list'] = object_list
    filterkategori = request.GET.get('filter')
    if(filterkategori):
        if(filterkategori=='organisasi'):
           context['table_list'] = Post.objects.filter(Organisasi=True)
        elif(filterkategori=='seminar'):
            context['table_list'] = Post.objects.filter(Seminar = True)
        elif(filterkategori=='lomba'):
            context['table_list']  = Post.objects.filter(Lomba = True)
    return render(request,'pages/index.html', context)

def post(request):
    posts = Post.objects.all(); 
    form = PostForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            u = form.save()
            return redirect(reverse('postevent'))
    context={
        'form' : form
    }
    return render(request,'pages/postevent.html', context)

sign/views.py
from django.shortcuts import render,redirect
from sign.forms import UserForm, RegisterForm
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_function
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
	if request.method == "POST":
		form = RegisterForm(request.POST)
		if form.is_valid():
			form.save()
		return render(request, "pages/index.html", {"form":form})
	else:
		form = RegisterForm()
	return render(request, "pages/register.html", {"form":form})

def login(request):
	if request.method == 'POST':
		form = UserForm(request.POST)
		user = authenticate(request, username = request.POST['username'], password = request.POST['password'])
		if user is not None:
			login_function(request, user)
			return HttpResponseRedirect(reverse('index'))
		else:
			return HttpResponse("please try again!")
	else:
		form = UserForm()
	return render(request, 'pages/login.html', {'form': form})

eventdetail/templates/pages/event.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' href="{% static 'bootstrap\css\bootstrap.css' %}">
    <link rel='stylesheet' href="{% static 'css\Event.css' %}">
    <link rel="stylesheet" href="{% static 'css\navbarUmum.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>PPW KC06</title>
</head>
<body>
    {% include 'pages/navbar2.html' %}

  <!-- <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Thumbnail Gallery</h1> -->

  <div class="container">
    <div class="" style="justify-content: center; display: flex;">
      <div class="" style="padding-top: 4% ;flex: 2">
        <div class="container" style="word-wrap: break-word;max-width: 500px">
                <h1 style="text-align: center">{{catch.nama_Kegiatan}}</h1>
                </br>
                {{catch.kategori}}
                {{catch.tanggal}}
                <hr style="border: 1px solid black"></hr>              
                {{catch.lokasi}}
                <hr style="border: 1px solid black"></hr>
                {{catch.contact}}
                <hr style="border: 1px solid black"></hr>              
          
        </div>
      </div>
      <div class="" style="padding-top: 4%; flex: 1;">
        <div class="container">
              <div class="" style="padding-top: 15%; word-wrap: break-word;max-width: 300px">
                <h6 style="font-weight: bold; ">Deskripsi Event</h6>
                {{catch.deskripsi}}
                <h6 style="font-weight: bold; margin-top: 10%;">Syarat dan Ketentuan</h6>
                {{catch.syarat_dan_ketentuan}}
            </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

home/templates/pages/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' href="{% static 'bootstrap\css\bootstrap.css' %}">
    <link rel='stylesheet' href="{% static 'css\Home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>PPW KC06</title>
</head>
<body>
    {% include 'pages/navbar.html' %}
  <h1 class="find-text">FIND YOUR EVENT HERE</h1>
    <form action="" method="get">
        <div class="input-group md-form form-sm form-2 pl-0">
            <input name = "q" class="form-control my-0 py-1 lime-border" type="text" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
            <button class="input-group-text lime lighten-2" id="basic-text1"><i class="fa fa-search" style="font-size:24px"></i></button>
            </div>
        </div>
        </form>
  </div>

<!-- Page Content -->
<div class="container">

  <!-- <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Thumbnail Gallery</h1> -->

  <hr class="mt-2 mb-5">  

  <div class="row text-center text-lg-left">
      {% for post in table_list %}
      <div class="col-lg-3 col-md-4 col-6">
          <a href="{% url 'post:details' post.id %}" class="d-block mb-4 h-100">
            <p class="event-title">{{post.nama_Kegiatan}}</p>
          </a>
          <p class="event-title">{{post.tanggal}}</p>
          <p class="event-title">{{post.lokasi}}</p> 
      </div>
      {% endfor %}
  </div>

</div>
<!-- /.container -->
</body>
</html>

home/templates/pages/login.html
{% block content %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' href="{% static 'bootstrap\css\bootstrap.css' %}">
    <link rel='stylesheet' href="{% static 'css\login.css' %}">
    <link rel='stylesheet' href="{% static 'css\navbarUmum.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>PPW KC06</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body>
{% include 'pages/navbar.html' %}
    <div class="container" style="align-items: center; margin-left: 23%;">
        <div class="formlogres" style="align-items: center; width: 100%">
            <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel-body"">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                       
                        <div class="form-group clearfix" style="display: flex; flex-direction: column;">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right"><font  color="white"> Username:</font><span class="text-red">*</span>:</label>
                            <div class="inputt" style="flex: 2; margin-left: 10px; margin-right: 10px;">
                                {{ form.username }}
                            </div>
                            <div class="inputt2" style="flex: 1"></div>
                        </div>
                        <div class="form-group clearfix" style="display: flex; flex-direction: column;">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right"><font color="white">Password:</font><span class="text-red">*</span>:</label>
                            <div class="inputt" style="flex: 2; margin-left: 10px; margin-right: 10px;">
                                {{ form.password }}
                            </div>
                            <div class="inputt2" style="flex: 1"></div>
                        </div>
                        <div class="col-md-6 col-md-offset-4" style="display: flex; flex-direction: row;">
                            <input type="submit" value="Login" class="btn btn-success" style="flex: 1; margin-bottom: 15px;">
                            <a class="panel-heading" href = "{% url 'register' %}" value= "w3docs" style="margin-left: 10%; flex: 1; color: rgba(221, 221, 221, 1)">Register</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

home/templates/pages/navbar.html
{% load staticfiles %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light blue-grey lighten-5 mb-4">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="{% url 'index' %}">CS POST</a>    
      
        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
      
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login'%}">Masuk</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'postevent' %}">Buat Event</a>
            </li>
      
            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Kategori</a>
              <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/?filter=organisasi">Organisasi</a>
                <a class="dropdown-item" href="/?filter=seminar">Seminar & Talkshow</a>
                <a class="dropdown-item" href="/?filter=lomba">Lomba</a>
              </div>
            </li>
      
          </ul>
          <!-- Links -->
      
          <!-- Search form -->
          <!-- <form class="form-inline">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>
        </div> -->
        <!-- Collapsible content -->
      
      </nav>
      <!--/.Navbar-->

home/templates/pages/navbar2.html
{% load staticfiles %}
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light blue-grey lighten-5 mb-4">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="{% url 'index' %}">CS POST</a>    
      
        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
      
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Masuk</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'postevent' %}">Buat Event</a>
            </li>
      
            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Kategori</a>
              <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/?filter=organisasi">Organisasi</a>
                <a class="dropdown-item" href="/?filter=seminar">Seminar & Talkshow</a>
                <a class="dropdown-item" href="/?filter=lomba">Lomba</a>
              </div>
            </li>
      
          </ul>
          <!-- Links -->
        <!-- Collapsible content -->
      
      </nav>
      <!--/.Navbar-->

home/templates/pages/register.html
{% block content %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' href="{% static 'bootstrap\css\bootstrap.css' %}">
    <link rel='stylesheet' href="{% static 'css\login.css' %}">
    <link rel='stylesheet' href="{% static 'css\navbarUmum.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>PPW KC06</title>
</head>
<body>
{% include 'pages/navbar.html' %}
    <div class="container" style="align-items: center; margin-left: 23%;">
        <div class="formlogres" style="align-items: center; width: 100%">
            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel-body"">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                       
                        <div class="form-group clearfix" style="display: flex; flex-direction: column;">
                            <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right"><font  color="white"> Username:</font><span class="text-red">*</span>:</label>
                            <div class="inputt" style="flex: 2; margin-left: 10px; margin-right: 10px; width: 45%;">
                                {{ form.username }}
                            </div>
                            <div class="inputt2" style="flex: 3"></div>
                        </div>
                        <div class="form-group clearfix" style="display: flex; flex-direction: column;">
                            <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right"><font color="white">Password:</font><span class="text-red">*</span>:</label>
                            <div class="inputt" style="flex: 2; margin-left: 10px; margin-right: 10px; width: 45%;">
                                {{ form.password }}
                            </div>
                            <div class="inputt2" style="flex: 1"></div>
                        </div>
                        <div class="form-group clearfix" style="display: flex; flex-direction: column;">
                            <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right"><font color="white">ConfirmPassword:</font><span class="text-red">*</span>:</label>
                            <div class="inputt" style="flex: 2; margin-left: 10px; margin-right: 10px; width: 45%;">
                                {{ form.password_repeat }}
                            </div>
                            <div class="inputt2" style="flex: 1"></div>
                        </div>
                        <div class="col-md-6 col-md-offset-4" style="display: flex; flex-direction: row;">
                            <input type="submit" value="Login" class="btn btn-success" style="flex: 2; margin-bottom: 15px;">
                            <a class="panel-heading" href = "{% url 'register' %}" value= "w3docs" style="margin-left: 190px; flex: 1; color: rgba(221, 221, 221, 1)">  </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

post/templates/pages/postevent.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' href="{% static 'bootstrap\css\bootstrap.css' %}">
    <link rel='stylesheet' href="{% static 'css\Home.css' %}">
    <link rel='stylesheet' href="{% static 'css\navbarUmum.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'pages/navbar2.html' %}
    <div class="container" style="display : flex;">
        <form action="{% url 'postevent' %}" method="post" class="form-inline" style="margin: auto; margin-top:20px; padding: 20px; flex-direction: column;">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <button type="submit" >Submit</button>
        </form>
    </div>
   <!--  <div class="container">
        <button type="button" style="justify-items: center; margin-left: 490px; margin-bottom: 30px; ">Submit</button>
    </div>
     -->
    <script src="{% static 'js/main.js' %}"></script>
</body>
    